# available options https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 1m

  # include test files or not, default is true
  tests: true

  # list of build tags, all linters use it. Default is empty list.
  build-tags:
    - test

  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #   	vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs:
    - vendor

# all available settings of specific linters
linters-settings:
  gocyclo:
    min-complexity: 25
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US  
linters:
  enable-all: true
  disable:
    - dupl
    - lll