project_name: godown
git:
  short_hash: true
release:
  name_template: "v{{ .Version }}"
  prerelease: true 
builds:
  -
    main: ./cmd/godown-cli/main.go
    binary: godown-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
  -
    main: ./cmd/godown-server/main.go
    binary: godown-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - 386
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
dist: build/dist
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
